# Generated by Django 3.0.2 on 2020-01-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
