# Generated by Django 3.0.2 on 2020-01-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.TextField(default='https://www.schild.de/wp-content/uploads/2016/08/nopic.jpg'),
        ),
    ]
